### PR TITLE
add BridleNSIS support

### PR DESCRIPTION
**Pull request by idleberg**

### CODE REVIEW

**Review by manuelbieh — CHANGES_REQUESTED** [review]
I dont see any Icon SVGs?

**Comment by idleberg** [comment]
Same icon as for NSIS, these are just additional file extensions that IMHO should be added. I don't know why the developer of the BridleNSIS transpiler decided to use a custom file-extension for its resulting files, but they are vanilla NSIS, so no need for a different icon.

**Comment by manuelbieh** [comment]
Ah, sure. I didnt have in mind that we already support nsis and the logo already exists. Sorry ;)

**Comment by manuelbieh** [comment]
Published in v1.7.1

**Pull request merged**
